"""Online video downloader for FrameLearn.

The download strategies are ported / adapted from the BiliNote project:

* Bilibili / YouTube: yt-dlp (BiliNote uses the same yt-dlp options).
* Bilibili: applies BiliNote's ``bilibili_dm_patch`` for the wbi/playurl
  risk-control parameters.
* Douyin: BiliNote's web aweme-detail API, with a small improvement — the
  fresh ``ttwid`` / ``msToken`` cookies generated by BiliNote's helper
  endpoints are actually attached to the API request.  Without them the
  detail API now returns an empty body.  yt-dlp is the fallback.
* Kuaishou: BiliNote's GraphQL ``visionVideoDetail`` flow.

Online subtitle discovery is also ported from two reference projects:

* YouTube uses ``youtube-digest``'s Supadata native-transcript flow
  (``lang=en`` / ``mode=native``, async polling for long videos).
* Bilibili uses ``Bilitato``'s ``x/player/v2`` subtitle flow (pick Chinese
  first, download the subtitle JSON and convert ``from/to/content`` to SRT).
"""

from __future__ import annotations

import json
import logging
import os
import re
import tempfile
import time
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path
from urllib.parse import parse_qs, urlencode, urlparse

import httpx
import yt_dlp

from framelearn.config import get as config_get
from framelearn.errors import DownloadError

from .bilibili_dm_patch import apply_bilibili_dm_img_patch
from .url_parser import (
    USER_AGENT,
    canonical_douyin_url,
    detect_platform,
    extract_url,
    extract_video_id,
    is_supported_video_url,
)

logger = logging.getLogger(__name__)

DOUYIN_MS_TOKEN_URL = "https://mssdk.bytedance.com/web/report"
DOUYIN_TTWID_URL = "https://ttwid.bytedance.com/ttwid/union/register/"
DOUYIN_MS_TOKEN_STR_DATA = "fWOdJTQR3/jwmZqBBsPO6tdNEc1jX7YTwPg0Z8CT+j3HScLFbj2Zm1XQ7/lqgSutntVKLJWaY3Hc/+vc0h+So9N1t6EqiImu5jKyUa+S4NPy6cNP0x9CUQQgb4+RRihCgsn4QyV8jivEFOsj3N5zFQbzXRyOV+9aG5B5EAnwpn8C70llsWq0zJz1VjN6y2KZiBZRyonAHE8feSGpwMDeUTllvq6BG3AQZz7RrORLWNCLEoGzM6bMovYVPRAJipuUML4Hq/568bNb5vqAo0eOFpvTZjQFgbB7f/CtAYYmnOYlvfrHKBKvb0TX6AjYrw2qmNNEer2ADJosmT5kZeBsogDui8rNiI/OOdX9PVotmcSmHOLRfw1cYXTgwHXr6cJeJveuipgwtUj2FNT4YCdZfUGGyRDz5bR5bdBuYiSRteSX12EktobsKPksdhUPGGv99SI1QRVmR0ETdWqnKWOj/7ujFZsNnfCLxNfqxQYEZEp9/U01CHhWLVrdzlrJ1v+KJH9EA4P1Wo5/2fuBFVdIz2upFqEQ11DJu8LSyD43qpTok+hFG3Moqrr81uPYiyPHnUvTFgwA/TIE11mTc/pNvYIb8IdbE4UAlsR90eYvPkI+rK9KpYN/l0s9ti9sqTth12VAw8tzCQvhKtxevJRQntU3STeZ3coz9Dg8qkvaSNFWuBDuyefZBGVSgILFdMy33//l/eTXhQpFrVc9OyxDNsG6cvdFwu7trkAENHU5eQEWkFSXBx9Ml54+fa3LvJBoacfPViyvzkJworlHcYYTG392L4q6wuMSSpYUconb+0c5mwqnnLP6MvRdm/bBTaY2Q6RfJcCxyLW0xsJMO6fgLUEjAg/dcqGxl6gDjUVRWbCcG1NAwPCfmYARTuXQYbFc8LO+r6WQTWikO9Q7Cgda78pwH07F8bgJ8zFBbWmyrghilNXENNQkyIzBqOQ1V3w0WXF9+Z3vG3aBKCjIENqAQM9qnC14WMrQkfCHosGbQyEH0n/5R2AaVTE/ye2oPQBWG1m0Gfcgs/96f6yYrsxbDcSnMvsA+okyd6GfWsdZYTIK1E97PYHlncFeOjxySjPpfy6wJc4UlArJEBZYmgveo1SZAhmXl3pJY3yJa9CmYImWkhbpwsVkSmG3g11JitJXTGLIfqKXSAhh+7jg4HTKe+5KNir8xmbBI/DF8O/+diFAlD+BQd3cV0G4mEtCiPEhOvVLKV1pE+fv7nKJh0t38wNVdbs3qHtiQNN7JhY4uWZAosMuBXSjpEtoNUndI+o0cjR8XJ8tSFnrAY8XihiRzLMfeisiZxWCvVwIP3kum9MSHXma75cdCQGFBfFRj0jPn1JildrTh2vRgwG+KeDZ33BJ2VGw9PgRkztZ2l/W5d32jc7H91FftFFhwXil6sA23mr6nNp6CcrO7rOblcm5SzXJ5MA601+WVicC/g3p6A0lAnhjsm37qP+xGT+cbCFOfjexDYEhnqz0QZm94CCSnilQ9B/HBLhWOddp9GK0SABIk5i3xAH701Xb4HCcgAulvfO5EK0RL2eN4fb+CccgZQeO1Zzo4qsMHc13UG0saMgBEH8SqYlHz2S0CVHuDY5j1MSV0nsShjM01vIynw6K0T8kmEyNjt1eRGlleJ5lvE8vonJv7rAeaVRZ06rlYaxrMT6cK3RSHd2liE50Z3ik3xezwWoaY6zBXvCzljyEmqjNFgAPU3gI+N1vi0MsFmwAwFzYqqWdk3jwRoWLp//FnawQX0g5T64CnfAe/o2e/8o5/bvz83OsAAwZoR48GZzPu7KCIN9q4GBjyrePNx5Csq2srblifmzSKwF5MP/RLYsk6mEE15jpCMKOVlHcu0zhJybNP3AKMVllF6pvn+HWvUnLXNkt0A6zsfvjAva/tbLQiiiYi6vtheasIyDz3HpODlI+BCkV6V8lkTt7m8QJ1IcgTfqjQBummyjYTSwsQji3DdNCnlKYd13ZQa545utqu837FFAzOZQhbnC3bKqeJqO2sE3m7WBUMbRWLflPRqp/PsklN+9jBPADKxKPl8g6/NZVq8fB1w68D5EJlGExdDhglo4B0aihHhb1u3+zJ2DqkxkPCGBAZ2AcuFIDzD53yS4NssoWb4HJ7YyzPaJro+tgG9TshWRBtUw8Or3m0OtQtX+rboYn3+GxvD1O8vWInrg5qxnepelRcQzmnor4rHF6ZNhAJZAf18Rjncra00HPJBugY5rD+EwnN9+mGQo43b01qBBRYEnxy9JJYuvXxNXxe47/MEPOw6qsxN+dmyIWZSuzkw8K+iBM/anE11yfU4qTFt0veCaVprK6tXaFK0ZhGXDOYJd70sjIP4UrPhatp8hqIXSJ2cwi70B+TvlDk/o19CA3bH6YxrAAVeag1P9hmNlfJ7NxK3Jp7+Ny1Vd7JHWVF+R6rSJiXXPfsXi3ZEy0klJAjI51NrDAnzNtgIQf0V8OWeEVv7F8Rsm3/GKnjdNOcDKymi9agZUgtctENWbCXGFnI40NHuVHtBRZeYAYtwfV7v6U0bP9s7uZGpkp+OETHMv3AyV0MVbZwQvarnjmct4Z3Vma+DvT+Z4VlMVnkC2x2FLt26K3SIMz+KV2XLv5ocEdPFSn1vMR7zruCWC8XqAG288biHo/soldmb/nlw8o8qlfZj4h296K3hfdFubGIUtqgsrZCrLCkkRC08Cv1ozEX/y6t2YrQepwiNmwDVk5IufStVvJMj+y2r9TcYLv7UKWXx3P6aySvM2ZHPaZhv+6Z/A/jIMBSvOizn4qG11iK7Oo6JYhxCSMJZsetjsnL4ecSIAufEmoFlAScWBh6nFArRpVLvkAZ3tej7H2lWFRXIU7x7mdBfGqU82PpM6znKMMZCpEsvHqpkSPSL+Kwz2z1f5wW7BKcKK4kNZ8iveg9VzY1NNjs91qU8DJpUnGyM04C7KNMpeilEmoOxvyelMQdi85ndOVmigVKmy5JYlODNX744sHpeqmMEK/ux3xY5O406lm7dZlyGPSMrFWbm4rzqvSEIskP43+9xVP8L84GeHE4RpOHg3qh/shx+/WnT1UhKuKpByHCpLoEo144udpzZswCYSMp58uPrlwdVF31//AacTRk8dUP3tBlnSQPa1eTpXWFCn7vIiqOTXaRL//YQK+e7ssrgSUnwhuGKJ8aqNDgdsL+haVZnV9g5Qrju643adyNixvYFEp0uxzOzVkekOMh2FYnFVIL2mJYGpZEXlAIC0zQbb54rSP89j0G7soJ2HcOkD0NmMEWj/7hUdTuMin1lRNde/qmHjwhbhqL8Z9MEO/YG3iLMgFTgSNQQhyE8AZAAKnehmzjORJfbK+qxyiJ07J843EDduzOoYt9p/YLqyTFmAgpdfK0uYrtAJ47cbl5WWhVXp5/XUxwWdL7TvQB0Xh6ir1/XBRcsVSDrR7cPE221ThmW1EPzD+SPf2L2gS0WromZqj1PhLgk92YnnR9s7/nLBXZHPKy+fDbJT16QqabFKqAl9G0blyf+R5UGX2kN+iQp4VGXEoH5lXxNNTlgRskzrW7KliQXcac20oimAHUE8Phf+rXXglpmSv4XN3eiwfXwvOaAMVjMRmRxsKitl5iZnwpcdbsC4jt16g2r/ihlKzLIYju+XZej4dNMlkftEidyNg24IVimJthXY1H15RZ8Hm7mAM/JZrsxiAVI0A49pWEiUk3cyZcBzq/vVEjHUy4r6IZnKkRvLjqsvqWE95nAGMor+F0GLHWfBCVkuI51EIOknwSB1eTvLgwgRepV4pdy9cdp6iR8TZndPVCikflXYVMlMEJ2bJ2c0Swiq57ORJW6vQwnkxtPudpFRc7tNNDzz4LKEznJxAwGi6pBR7/co2IUgRw1ijLFTHWHQJOjgc7KaduHI0C6a+BJb4Y8IWuIk2u2qCMF1HNKFAUn/J1gTcqtIJcvK5uykpfJFCYc899TmUc8LMKI9nu57m0S44Y2hPPYeW4XSakScsg8bJHMkcXk3Tbs9b4eqiD+kHUhTS2BGfsHadR3d5j8lNhBPzA5e+mE=="

DOUYIN_TTWID_DATA = (
    '{"region":"cn","aid":1768,"needFid":false,'
    '"service":"www.ixigua.com","migrate_info":{"ticket":"","source":"node"},'
    '"cbUrlProtocol":"https","union":true}'
)

KUAISHOU_GRAPHQL_URL = "https://www.kuaishou.com/graphql"
KUAISHOU_GRAPHQL_QUERY = "query visionVideoDetail($photoId: String, $type: String, $page: String, $webPageArea: String) {\n  visionVideoDetail(photoId: $photoId, type: $type, page: $page, webPageArea: $webPageArea) {\n    status\n    type\n    author {\n      id\n      name\n      following\n      headerUrl\n      __typename\n    }\n    photo {\n      id\n      duration\n      caption\n      likeCount\n      realLikeCount\n      coverUrl\n      photoUrl\n      liked\n      timestamp\n      expTag\n      llsid\n      viewCount\n      videoRatio\n      stereoType\n      croppedPhotoUrl\n      manifest {\n        mediaType\n        businessType\n        version\n        adaptationSet {\n          id\n          duration\n          representation {\n            id\n            defaultSelect\n            backupUrl\n            codecs\n            url\n            height\n            width\n            avgBitrate\n            maxBitrate\n            m3u8Slice\n            qualityType\n            qualityLabel\n            frameRate\n            featureP2sp\n            hidden\n            disableAdaptive\n            __typename\n          }\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    tags {\n      type\n      name\n      __typename\n    }\n    commentLimit {\n      canAddComment\n      __typename\n    }\n    llsid\n    danmakuSwitch\n    __typename\n  }\n}\n"

KUAISHOU_HEADERS = {
    "Accept-Language": "zh-CN,zh;q=0.9",
    "Cache-Control": "no-cache",
    "Connection": "keep-alive",
    "Origin": "https://www.kuaishou.com",
    "Pragma": "no-cache",
    "Referer": "https://www.kuaishou.com/",
    "User-Agent": USER_AGENT,
    "accept": "*/*",
    "content-type": "application/json",
    "sec-ch-ua": '"Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126"',
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": '"Windows"',
}


@dataclass
class DownloadedSubtitle:
    """Subtitle file found for an online video."""

    path: Path
    language: str | None = None
    source: str | None = None


@dataclass
class DownloadedVideo:
    """A video that has been downloaded to a local path."""

    video_path: Path
    source_url: str
    platform: str
    video_id: str = ""
    title: str = ""
    duration: float | None = None
    thumbnail: str | None = None
    subtitle_path: Path | None = None
    subtitle_language: str | None = None
    subtitle_source: str | None = None
    warnings: list[str] = field(default_factory=list)


def _duration_seconds(raw: object) -> float | None:
    """Platform APIs usually report duration in milliseconds."""
    try:
        return float(raw) / 1000.0  # type: ignore[arg-type]
    except (TypeError, ValueError):
        return None


# ---------------------------------------------------------------------------
# configuration helpers
# ---------------------------------------------------------------------------


def _download_dir() -> Path:
    env_dir = os.getenv("DOWNLOAD_DIR", "").strip()
    raw = env_dir or str(config_get("download.download_dir", "./downloads") or "./downloads")
    path = Path(raw).expanduser()
    path.mkdir(parents=True, exist_ok=True)
    return path


def _proxy_url() -> str | None:
    env_proxy = os.getenv("DOWNLOAD_PROXY", "").strip()
    if env_proxy:
        return env_proxy
    configured = str(config_get("download.proxy", "") or "").strip()
    if configured:
        return configured
    for key in (
        "HTTPS_PROXY",
        "https_proxy",
        "HTTP_PROXY",
        "http_proxy",
        "ALL_PROXY",
        "all_proxy",
    ):
        value = os.getenv(key, "").strip()
        if value:
            return value
    return None


def _client_proxy_kwargs() -> dict:
    """httpx.Client kwargs for the configured download proxy (if any)."""
    proxy = _proxy_url()
    return {"proxies": proxy} if proxy else {}


def _platform_env(platform: str, *keys: str) -> str:
    for key in keys:
        value = os.getenv(key, "").strip()
        if value:
            return value
    return ""


def _parse_cookie_string(raw_cookie: str) -> dict[str, str]:
    cookies: dict[str, str] = {}
    for part in raw_cookie.split(";"):
        if "=" in part:
            key, value = part.strip().split("=", 1)
            if key:
                cookies[key] = value
    return cookies


def _write_netscape_cookie_file(cookies: dict[str, str], domain: str) -> Path:
    """Write a temporary Netscape cookie file for yt-dlp."""
    domain_field = domain if domain.startswith(".") else f".{domain}"
    expiry = int(time.time()) + 365 * 24 * 3600
    lines = ["# Netscape HTTP Cookie File"]
    for name, value in cookies.items():
        lines.append(
            f"{domain_field}\tTRUE\t/\tFALSE\t{expiry}\t{name}\t{value}"
        )
    fd, name = tempfile.mkstemp(prefix="framelearn_cookies_", suffix=".txt")
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return Path(name)


def _cleanup(paths: list[Path]) -> None:
    for path in paths:
        try:
            path.unlink(missing_ok=True)
        except OSError:
            pass


# ---------------------------------------------------------------------------
# generic yt-dlp downloader (Bilibili / YouTube / fallbacks)
# ---------------------------------------------------------------------------

_YTDLP_FORMATS = {
    "youtube": "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]/bestvideo+bestaudio/best",
    "bilibili": "bv*[ext=mp4]/bestvideo+bestaudio/best",
    "douyin": "bestvideo+bestaudio/best",
    "kuaishou": "bestvideo+bestaudio/best",
}


def _configured_cookie_file(platform: str, cleanup_paths: list[Path]) -> Path | None:
    raw_cookie = _platform_env(
        platform,
        f"{platform.upper()}_COOKIE",
        f"{platform.upper()}_COOKIE_FILE",
    )
    if not raw_cookie:
        return None

    candidate = Path(raw_cookie).expanduser()
    if candidate.is_file():
        return candidate

    cookies = _parse_cookie_string(raw_cookie)
    if not cookies:
        return None
    path = _write_netscape_cookie_file(cookies, _cookie_domain(platform))
    cleanup_paths.append(path)
    return path


def _cookie_domain(platform: str) -> str:
    return {
        "youtube": ".youtube.com",
        "bilibili": ".bilibili.com",
        "douyin": ".douyin.com",
        "kuaishou": ".kuaishou.com",
    }.get(platform, ".example.com")


def _ytdlp_options(
    platform: str,
    output_dir: Path,
    cookiefile: Path | None = None,
) -> dict:
    proxy = _proxy_url()
    opts: dict = {
        "format": _YTDLP_FORMATS.get(platform, "bestvideo+bestaudio/best"),
        "outtmpl": str(output_dir / "%(id)s.%(ext)s"),
        "noplaylist": True,
        "merge_output_format": "mp4",
        "noprogress": True,
        "quiet": False,
        "overwrites": False,
        "retries": 5,
        "fragment_retries": 5,
        "writesubtitles": True,
        "writeautomaticsub": True,
        "subtitleslangs": ["zh.*", "en.*"],
        "subtitlesformat": "srt/vtt/best",
    }
    if proxy:
        opts["proxy"] = proxy
    if cookiefile:
        opts["cookiefile"] = str(cookiefile)
    if platform == "bilibili":
        opts["http_headers"] = {"Referer": "https://www.bilibili.com"}
    return opts


def _existing_file(output_dir: Path, video_id: str) -> Path | None:
    if not video_id:
        return None
    for ext in (".mp4", ".mkv", ".webm", ".mov", ".flv"):
        candidate = output_dir / f"{video_id}{ext}"
        if candidate.exists() and candidate.stat().st_size > 0:
            return candidate
    return None


def _locate_downloaded_file(output_dir: Path, video_id: str) -> Path | None:
    existing = _existing_file(output_dir, video_id)
    if existing:
        return existing

    candidates = sorted(
        output_dir.glob(f"{video_id}.*"),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    excluded_suffixes = (".part", ".ytdl", ".temp", ".info.json", ".description")
    video_extensions = (".mp4", ".mkv", ".webm", ".mov", ".flv", ".m4v")
    for candidate in candidates:
        if candidate.suffix.lower() in excluded_suffixes or candidate.stat().st_size <= 0:
            continue
        if candidate.suffix.lower() in video_extensions:
            return candidate
    return None



# ---------------------------------------------------------------------------
# Online subtitle discovery
#
# Two project behaviours are ported here:
# * YouTube follows ``youtube-digest``: Supadata's native transcript API is
#   called with ``lang=en`` / ``mode=native``, and its timestamped chunks are
#   converted to SRT. ``>>`` speaker markers from YouTube auto-captions are
#   removed exactly like youtube-digest does.
# * Bilibili follows ``Bilitato``: query ``x/player/pagelist`` for the CID,
#   then ``x/player/v2`` for subtitle options, pick Chinese first, download
#   the subtitle JSON and convert ``body[].from/to/content`` rows to SRT.
# ---------------------------------------------------------------------------

SUPADATA_TRANSCRIPT_URL = "https://api.supadata.ai/v1/transcript"
SUPADATA_POLL_INTERVAL = 1.0
SUPADATA_POLL_MAX_ATTEMPTS = 60

BILIBILI_PAGELIST_URL = "https://api.bilibili.com/x/player/pagelist"
BILIBILI_PLAYER_V2_URL = "https://api.bilibili.com/x/player/v2"

_SUBTITLE_SUFFIXES = (".srt", ".vtt")


def _format_srt_time(seconds: float) -> str:
    """Format seconds as ``HH:MM:SS,mmm``."""
    ms = max(0, round(float(seconds) * 1000))
    h, rem = divmod(ms, 3_600_000)
    m, rem = divmod(rem, 60_000)
    s, ms = divmod(rem, 1000)
    return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"


def _write_srt(path: Path, rows: list[tuple[float, float, str]]) -> Path:
    """Write ``(start, end, text)`` rows to an SRT file."""
    lines: list[str] = []
    for index, (start, end, text) in enumerate(rows, start=1):
        lines.append(str(index))
        lines.append(f"{_format_srt_time(start)} --> {_format_srt_time(end)}")
        lines.append(text.strip())
        lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines).strip() + "\n", encoding="utf-8")
    return path


def _supadata_chunks_to_rows(data: dict) -> list[tuple[float, float, str]]:
    """Convert Supadata ``content`` chunks to SRT rows.

    ``offset`` / ``duration`` are milliseconds. This mirrors youtube-digest:
    strip the ``>>`` speaker marker and skip now-empty chunks.
    """
    rows: list[tuple[float, float, str]] = []
    if not isinstance(data, dict):
        return rows
    for chunk in data.get("content") or []:
        if not isinstance(chunk, dict):
            continue
        text = str(chunk.get("text") or "").replace(">>", "").strip()
        if not text:
            continue
        start = float(chunk.get("offset") or 0) / 1000.0
        duration = float(chunk.get("duration") or 0) / 1000.0
        end = start + max(duration, 0.2)
        rows.append((start, end, text))
    return rows


def _poll_supadata_job(
    client: httpx.Client, job_id: str, api_key: str
) -> dict:
    """Poll a Supadata async transcript job (port of youtube-digest)."""
    if not job_id:
        raise DownloadError("Supadata returned an empty transcript job id")
    url = f"{SUPADATA_TRANSCRIPT_URL}/{job_id}"
    for _ in range(SUPADATA_POLL_MAX_ATTEMPTS):
        time.sleep(SUPADATA_POLL_INTERVAL)
        response = client.get(url, headers={"x-api-key": api_key})
        if not response.is_success:
            raise DownloadError(
                f"Supadata job polling failed: HTTP {response.status_code}"
            )
        data = response.json()
        if not isinstance(data, dict):
            raise DownloadError("Supadata returned an unexpected job payload")
        status = data.get("status")
        if status == "completed":
            return data
        if status == "failed":
            raise DownloadError("Supadata transcript processing failed")
    raise DownloadError("Supadata transcript processing timed out")


def _fetch_supadata_subtitle(
    video_id: str, output_dir: Path
) -> DownloadedSubtitle | None:
    """Fetch native YouTube subtitles from Supadata (youtube-digest style).

    English is requested explicitly, matching youtube-digest's
    ``lang=en&mode=native`` request. No key or no native track returns None
    so the caller can fall back to yt-dlp subtitles or ASR.
    """
    api_key = os.getenv("SUPADATA_API_KEY", "").strip()
    if not api_key:
        return None

    params = {
        "url": f"https://www.youtube.com/watch?v={video_id}",
        "text": "false",
        "lang": "en",
        "mode": "native",
    }
    headers = {
        "x-api-key": api_key,
        "User-Agent": USER_AGENT,
    }
    try:
        with httpx.Client(
            follow_redirects=True,
            timeout=httpx.Timeout(30.0),
            **_client_proxy_kwargs(),
        ) as client:
            response = client.get(
                SUPADATA_TRANSCRIPT_URL, params=params, headers=headers
            )

            if response.status_code == 202:
                job = response.json()
                data = _poll_supadata_job(
                    client, str(job.get("jobId") or ""), api_key
                )
            elif response.status_code in (206, 404):
                return None
            elif not response.is_success:
                logger.warning(
                    "Supadata transcript request failed: HTTP %s",
                    response.status_code,
                )
                return None
            else:
                data = response.json()
    except (httpx.HTTPError, DownloadError, ValueError) as e:
        logger.warning("Supadata transcript unavailable: %s", e)
        return None

    rows = _supadata_chunks_to_rows(data)
    if not rows:
        return None

    language = str(data.get("lang") or "en")
    path = _write_srt(
        output_dir / f"{video_id}.{language}.srt",
        rows,
    )
    return DownloadedSubtitle(path=path, language=language, source="supadata")


def _bilibili_cookie_value() -> str:
    """Return a Cookie header value for Bilibili API calls."""
    raw = _platform_env(
        "bilibili", "BILIBILI_COOKIE", "BILIBILI_COOKIE_FILE"
    )
    if not raw:
        return ""
    candidate = Path(raw).expanduser()
    if candidate.is_file():
        cookies: list[str] = []
        for line in candidate.read_text(encoding="utf-8").splitlines():
            parts = line.split("\t")
            if len(parts) < 7 or not parts[0].endswith("bilibili.com"):
                continue
            cookies.append(f"{parts[5]}={parts[6]}")
        return "; ".join(cookies)
    return raw


def _bilibili_headers() -> dict[str, str]:
    headers = {
        "User-Agent": USER_AGENT,
        "Referer": "https://www.bilibili.com",
    }
    cookie = _bilibili_cookie_value()
    if cookie:
        headers["Cookie"] = cookie
    return headers


def _bilibili_cid(video_id: str, page: int = 1) -> int | None:
    """Resolve the CID for a Bilibili video/page."""
    try:
        with httpx.Client(
            follow_redirects=True,
            timeout=httpx.Timeout(20.0),
            **_client_proxy_kwargs(),
        ) as client:
            response = client.get(
                BILIBILI_PAGELIST_URL,
                params={"bvid": video_id, "jsonp": "jsonp"},
                headers=_bilibili_headers(),
            )
            if not response.is_success:
                return None
            payload = response.json()
            if not isinstance(payload, dict):
                return None
            pages = payload.get("data") or []
            if not pages:
                return None
            page = max(1, min(page, len(pages)))
            cid = pages[page - 1].get("cid")
            return int(cid) if cid else None
    except (httpx.HTTPError, ValueError):
        return None


def _bilibili_subtitle_options(data: dict) -> list[dict]:
    """Normalise Bilibili subtitle entries (Bilitato's option logic)."""
    if not isinstance(data, dict):
        return []
    raw_items = (
        ((data.get("data") or {}).get("subtitle") or {}).get("subtitles")
        or []
    )
    if not isinstance(raw_items, list):
        return []
    options: list[dict] = []
    for item in raw_items:
        if not isinstance(item, dict):
            continue
        raw_url = str(item.get("subtitle_url") or item.get("url") or "").strip()
        if not raw_url:
            continue
        url = f"https:{raw_url}" if raw_url.startswith("//") else raw_url
        lan = str(item.get("lan") or "").strip()
        lan_doc = str(item.get("lan_doc") or "").strip()
        options.append(
            {
                "id": lan or lan_doc or f"subtitle-{len(options) + 1}",
                "label": lan_doc or lan or f"字幕 {len(options) + 1}",
                "lan": lan,
                "url": url,
            }
        )
    return options


def _bilibili_subtitle_language(raw: str | None) -> str | None:
    text = f"{raw or ''} {raw or ''}".lower()
    if re.search(r"zh|cn|中文|汉语|简体|繁體", text):
        return "zh"
    if re.search(r"en|english|英文", text):
        return "en"
    return (raw or "").strip() or None


def _pick_bilibili_subtitle(options: list[dict]) -> dict | None:
    if not options:
        return None
    for lang in ("zh", "en"):
        for option in options:
            if _bilibili_subtitle_language(
                option.get("lan") or option.get("id")
            ) == lang:
                return option
    return options[0]


def _bilibili_subtitle_body(data: dict) -> list[dict]:
    """Extract ``body`` rows from Bilibili subtitle JSON responses."""
    if not isinstance(data, dict):
        return []
    candidates = (
        data.get("body"),
        (data.get("data") or {}).get("body"),
        (data.get("result") or {}).get("body"),
        data.get("content"),
    )
    for candidate in candidates:
        if isinstance(candidate, list):
            return candidate
    return []


def _bilibili_rows_to_srt_rows(
    body: list[dict],
) -> list[tuple[float, float, str]]:
    rows: list[tuple[float, float, str]] = []
    for row in body:
        if not isinstance(row, dict):
            continue
        text = str(row.get("content") or "").strip()
        if not text:
            continue
        start = float(row.get("from") or 0)
        raw_end = row.get("to")
        end = float(raw_end) if raw_end is not None else start + 3.0
        if end <= start:
            end = start + 3.0
        rows.append((start, end, text))
    return rows


def _fetch_bilibili_subtitle(
    video_id: str, output_dir: Path, page: int = 1
) -> DownloadedSubtitle | None:
    """Fetch Bilibili official subtitles (Bilitato's API flow)."""
    cid = _bilibili_cid(video_id, page=page)
    if not cid:
        return None

    try:
        with httpx.Client(
            follow_redirects=True,
            timeout=httpx.Timeout(20.0),
            **_client_proxy_kwargs(),
        ) as client:
            response = client.get(
                BILIBILI_PLAYER_V2_URL,
                params={"bvid": video_id, "cid": cid},
                headers=_bilibili_headers(),
            )
            if not response.is_success:
                return None
            data = response.json()
            options = _bilibili_subtitle_options(data)
            option = _pick_bilibili_subtitle(options)
            if option is None:
                return None

            subtitle_response = client.get(
                option["url"],
                headers=_bilibili_headers(),
            )
            if not subtitle_response.is_success:
                return None
            body = _bilibili_subtitle_body(subtitle_response.json())
    except (httpx.HTTPError, ValueError):
        return None

    rows = _bilibili_rows_to_srt_rows(body)
    if not rows:
        return None

    language = (
        _bilibili_subtitle_language(option.get("lan") or option.get("id"))
        or "und"
    )
    path = _write_srt(
        output_dir / f"{video_id}.{language}.srt",
        rows,
    )
    return DownloadedSubtitle(path=path, language=language, source="bilibili")


def _subtitle_language_from_filename(path: Path, video_id: str) -> str:
    name = path.name
    if name == f"{video_id}.srt" or name == f"{video_id}.vtt":
        return "und"
    prefix = f"{video_id}."
    if not name.startswith(prefix):
        return "und"
    stem = name[len(prefix):].rsplit(".", 1)[0]
    return _bilibili_subtitle_language(stem) or stem.lower()


def _find_local_subtitle(
    output_dir: Path,
    video_id: str,
    preferred_languages: tuple[str, ...] = ("zh", "en"),
) -> DownloadedSubtitle | None:
    """Pick the best yt-dlp-written subtitle file next to the video."""
    candidates = [
        path
        for path in output_dir.glob(f"{video_id}.*")
        if path.suffix.lower() in _SUBTITLE_SUFFIXES and path.stat().st_size > 0
    ]
    if not candidates:
        return None

    def sort_key(path: Path) -> tuple[int, int, int]:
        lang = _subtitle_language_from_filename(path, video_id)
        if lang in preferred_languages:
            lang_rank = preferred_languages.index(lang)
        else:
            lang_rank = len(preferred_languages)
        srt_rank = 0 if path.suffix.lower() == ".srt" else 1
        return (lang_rank, srt_rank, -path.stat().st_mtime)

    best = min(candidates, key=sort_key)
    return DownloadedSubtitle(
        path=best,
        language=_subtitle_language_from_filename(best, video_id),
        source="yt-dlp",
    )


def _lookup_subtitle(
    platform: str,
    video_id: str,
    output_dir: Path,
    bilibili_page: int = 1,
) -> DownloadedSubtitle | None:
    """Find an online subtitle for a downloaded video, or return None."""
    if not video_id:
        return None

    if platform == "youtube":
        supadata = _fetch_supadata_subtitle(video_id, output_dir)
        if supadata is not None:
            return supadata
        return _find_local_subtitle(
            output_dir, video_id, preferred_languages=("en", "zh")
        )

    if platform == "bilibili":
        bilibili = _fetch_bilibili_subtitle(
            video_id, output_dir, page=bilibili_page
        )
        if bilibili is not None:
            return bilibili

    return _find_local_subtitle(output_dir, video_id)


def _subtitle_fields(
    subtitle: DownloadedSubtitle | None,
) -> tuple[Path | None, str | None, str | None]:
    if subtitle is None:
        return None, None, None
    return subtitle.path, subtitle.language, subtitle.source


def _download_with_ytdlp(
    url: str,
    platform: str,
    output_dir: Path,
    cookiefile: Path | None = None,
    bilibili_page: int = 1,
) -> DownloadedVideo:
    cleanup_paths: list[Path] = []
    if cookiefile is None:
        cookiefile = _configured_cookie_file(platform, cleanup_paths)

    opts = _ytdlp_options(platform, output_dir, cookiefile=cookiefile)
    try:
        with yt_dlp.YoutubeDL(opts) as ydl:
            info = ydl.extract_info(url, download=True)
    finally:
        _cleanup(cleanup_paths)

    if info and info.get("_type") == "playlist" and info.get("entries"):
        info = info["entries"][0]

    video_id = str(info.get("id") or extract_video_id(url, platform) or "")
    video_path = _locate_downloaded_file(output_dir, video_id)
    if video_path is None:
        raise DownloadError(
            f"{platform} 视频下载完成，但未找到输出文件（video_id={video_id}）"
        )
    subtitle = _lookup_subtitle(
        platform,
        video_id,
        output_dir,
        bilibili_page=bilibili_page,
    )
    subtitle_path, subtitle_language, subtitle_source = _subtitle_fields(subtitle)
    return DownloadedVideo(
        video_path=video_path,
        source_url=url,
        platform=platform,
        video_id=video_id,
        title=str(info.get("title") or ""),
        duration=float(info["duration"]) if info.get("duration") else None,
        thumbnail=info.get("thumbnail"),
        subtitle_path=subtitle_path,
        subtitle_language=subtitle_language,
        subtitle_source=subtitle_source,
    )


# ---------------------------------------------------------------------------
# Bilibili
# ---------------------------------------------------------------------------


def _download_bilibili(url: str, output_dir: Path) -> DownloadedVideo:
    apply_bilibili_dm_img_patch()
    video_id = extract_video_id(url, "bilibili")
    page = int((parse_qs(urlparse(url).query).get("p") or ["1"])[0] or 1)
    existing = _existing_file(output_dir, video_id or "")
    if existing:
        print(f"⏭️  已下载过 B 站视频：{existing.name}")
        subtitle = _lookup_subtitle(
            "bilibili", video_id or "", output_dir, bilibili_page=page
        )
        subtitle_path, subtitle_language, subtitle_source = _subtitle_fields(subtitle)
        return DownloadedVideo(
            video_path=existing,
            source_url=url,
            platform="bilibili",
            video_id=video_id or "",
            subtitle_path=subtitle_path,
            subtitle_language=subtitle_language,
            subtitle_source=subtitle_source,
        )
    return _download_with_ytdlp(
        url, "bilibili", output_dir, bilibili_page=page
    )


# ---------------------------------------------------------------------------
# YouTube
# ---------------------------------------------------------------------------


def _download_youtube(url: str, output_dir: Path) -> DownloadedVideo:
    video_id = extract_video_id(url, "youtube")
    existing = _existing_file(output_dir, video_id or "")
    if existing:
        print(f"⏭️  已下载过 YouTube 视频：{existing.name}")
        subtitle = _lookup_subtitle("youtube", video_id or "", output_dir)
        subtitle_path, subtitle_language, subtitle_source = _subtitle_fields(subtitle)
        return DownloadedVideo(
            video_path=existing,
            source_url=url,
            platform="youtube",
            video_id=video_id or "",
            subtitle_path=subtitle_path,
            subtitle_language=subtitle_language,
            subtitle_source=subtitle_source,
        )
    return _download_with_ytdlp(url, "youtube", output_dir)


# ---------------------------------------------------------------------------
# Douyin
# ---------------------------------------------------------------------------


def _douyin_base_params(aweme_id: str, ms_token: str | None) -> dict:
    params = {
        "device_platform": "webapp",
        "aid": "6383",
        "channel": "channel_pc_web",
        "pc_client_type": 1,
        "version_code": "290100",
        "version_name": "29.1.0",
        "cookie_enabled": "true",
        "screen_width": 1920,
        "screen_height": 1080,
        "browser_language": "zh-CN",
        "browser_platform": "Win32",
        "browser_name": "Chrome",
        "browser_version": "130.0.0.0",
        "browser_online": "true",
        "engine_name": "Blink",
        "engine_version": "130.0.0.0",
        "os_name": "Windows",
        "os_version": "10",
        "cpu_core_num": 12,
        "device_memory": 8,
        "platform": "PC",
        "downlink": "10",
        "effective_type": "4g",
        "from_user_page": "1",
        "locate_query": "false",
        "need_time_list": "1",
        "pc_libra_divert": "Windows",
        "publish_video_strategy_type": "2",
        "round_trip_time": "0",
        "show_live_replay_strategy": "1",
        "time_list_query": "0",
        "whale_cut_token": "",
        "update_version_code": "170400",
        "aweme_id": aweme_id,
    }
    if ms_token:
        params["msToken"] = ms_token
    return params


def _bootstrap_douyin_cookies() -> dict[str, str]:
    """Create fresh Douyin visitor cookies.

    This follows BiliNote's DouyinDownloader endpoints (ttwid registration +
    mssdk msToken) and then attaches the generated cookies to the detail
    request.  The latter step is required now: the detail API returns an
    empty body when the cookies are generated but never sent.
    """
    cookies: dict[str, str] = {}
    headers = {
        "User-Agent": USER_AGENT,
        "Accept-Language": "zh-CN,zh;q=0.9",
        "Referer": "https://www.douyin.com/",
    }
    with httpx.Client(
        headers=headers,
        follow_redirects=True,
        timeout=httpx.Timeout(20.0),
        **_client_proxy_kwargs(),
    ) as client:
        try:
            client.get("https://www.douyin.com/")
        except httpx.HTTPError as e:
            logger.warning("获取抖音首页 Cookie 失败: %s", e)

        try:
            client.post(
                DOUYIN_TTWID_URL,
                content=DOUYIN_TTWID_DATA,
                headers={"Content-Type": "application/json"},
            )
        except httpx.HTTPError as e:
            logger.warning("注册抖音 ttwid 失败: %s", e)

        try:
            payload = json.dumps(
                {
                    "magic": 538969122,
                    "version": 1,
                    "dataType": 8,
                    "strData": DOUYIN_MS_TOKEN_STR_DATA,
                    "tspFromClient": int(time.time() * 1000),
                }
            )
            response = client.post(
                DOUYIN_MS_TOKEN_URL,
                content=payload,
                headers={"Content-Type": "application/json"},
            )
            for cookie in response.cookies.jar:
                if cookie.name == "msToken":
                    cookies[cookie.name] = cookie.value
        except httpx.HTTPError as e:
            logger.warning("获取抖音 msToken 失败: %s", e)

        for cookie in client.cookies.jar:
            if cookie.name in ("__ac_nonce", "ttwid"):
                cookies[cookie.name] = cookie.value

    return cookies


def _douyin_cookie_string() -> tuple[dict[str, str], str]:
    cookies = _bootstrap_douyin_cookies()
    configured = _platform_env("douyin", "DOUYIN_COOKIE")
    if configured:
        cookies.update(_parse_cookie_string(configured))
    cookie_string = "; ".join(f"{name}={value}" for name, value in cookies.items())
    return cookies, cookie_string


def _fetch_douyin_detail(video_id: str, cookie_string: str) -> dict:
    params = _douyin_base_params(
        video_id, _parse_cookie_string(cookie_string).get("msToken")
    )
    url = "https://www.douyin.com/aweme/v1/web/aweme/detail/?" + urlencode(params)
    headers = {
        "User-Agent": USER_AGENT,
        "Accept-Language": "zh-CN,zh;q=0.9",
        "Referer": "https://www.douyin.com/",
        "Cookie": cookie_string,
    }
    with httpx.Client(
        follow_redirects=True,
        timeout=httpx.Timeout(20.0),
        **_client_proxy_kwargs(),
    ) as client:
        response = client.get(url, headers=headers)
    if response.status_code != 200:
        raise DownloadError(f"抖音接口返回 HTTP {response.status_code}")
    if not response.content.strip():
        raise DownloadError("抖音接口返回空响应（可能需要设置 DOUYIN_COOKIE）")
    try:
        data = response.json()
    except json.JSONDecodeError as e:
        raise DownloadError(f"抖音接口返回非 JSON 响应：{response.text[:120]!r}") from e
    if not data.get("aweme_detail"):
        reason = (data.get("filter_detail") or {}).get("filter_reason", "")
        raise DownloadError(
            f"抖音未返回视频详情（{reason or '可能已删除或不可访问'}）"
        )
    return data


def _download_douyin(url: str, output_dir: Path) -> DownloadedVideo:
    canonical_url = canonical_douyin_url(url, proxy=_proxy_url())
    video_id = extract_video_id(canonical_url, "douyin") or ""
    existing = _existing_file(output_dir, video_id)
    if existing:
        print(f"⏭️  已下载过抖音视频：{existing.name}")
        return DownloadedVideo(
            video_path=existing,
            source_url=url,
            platform="douyin",
            video_id=video_id,
        )

    cookies, cookie_string = _douyin_cookie_string()

    # Preferred path: BiliNote's aweme-detail API + direct media URL.
    try:
        data = _fetch_douyin_detail(video_id, cookie_string)
        aweme = data["aweme_detail"]
        video = aweme.get("video") or {}
        urls = []
        for key in ("download_addr", "play_addr"):
            urls.extend(video.get(key, {}).get("url_list") or [])
        media_url = urls[0] if urls else None
        if media_url:
            target = output_dir / f"{video_id}.mp4"
            _stream_download(
                media_url,
                target,
                headers={
                    "User-Agent": USER_AGENT,
                    "Referer": "https://www.douyin.com/",
                },
            )
            return DownloadedVideo(
                video_path=target,
                source_url=url,
                platform="douyin",
                video_id=video_id,
                title=str(aweme.get("desc") or aweme.get("item_title") or ""),
                duration=_duration_seconds(video.get("duration")),
                thumbnail=(video.get("cover") or {}).get("url_list", [None])[0],
            )
    except DownloadError as e:
        logger.warning("抖音 API 直连下载失败，回退 yt-dlp：%s", e)

    # Fallback: yt-dlp with the freshly generated visitor cookie file.
    cleanup_paths: list[Path] = []
    cookiefile: Path | None = None
    if cookies:
        cookiefile = _write_netscape_cookie_file(cookies, ".douyin.com")
        cleanup_paths.append(cookiefile)
    try:
        return _download_with_ytdlp(
            canonical_url, "douyin", output_dir, cookiefile=cookiefile
        )
    finally:
        _cleanup(cleanup_paths)


def _stream_download(url: str, target: Path, headers: dict | None = None) -> None:
    """Download a media URL to ``target`` atomically-ish (tmp + rename)."""
    tmp = target.with_name(f".{target.name}.part")
    target.parent.mkdir(parents=True, exist_ok=True)
    merged = {"User-Agent": USER_AGENT}
    if headers:
        merged.update(headers)
    try:
        with httpx.Client(
            headers=merged,
            follow_redirects=True,
            timeout=httpx.Timeout(30.0, connect=30.0, read=None, write=60.0, pool=20.0),
            **_client_proxy_kwargs(),
        ) as client, client.stream("GET", url) as response:
            if response.status_code != 200:
                raise DownloadError(f"媒体下载失败：HTTP {response.status_code}")
            with tmp.open("wb") as f:
                for chunk in response.iter_bytes(1024 * 1024):
                    f.write(chunk)
        tmp.replace(target)
    except DownloadError:
        raise
    except httpx.HTTPError as e:
        raise DownloadError(f"媒体下载失败：{e}") from e
    finally:
        tmp.unlink(missing_ok=True)


# ---------------------------------------------------------------------------
# Kuaishou
# ---------------------------------------------------------------------------


def _kuaishou_cookie_string(client: httpx.Client) -> str:
    configured = _platform_env("kuaishou", "KUAISHOU_COOKIE")
    if configured:
        return configured

    # BiliNote's KuaiShou helper asks the homepage for visitor cookies.
    client.get("https://www.kuaishou.com/")
    pairs: list[str] = []
    for cookie in client.cookies.jar:
        domain = cookie.domain or ""
        if domain.endswith(("kuaishou.com", "chenzhongtech.com")):
            pairs.append(f"{cookie.name}={cookie.value}")
    return "; ".join(pairs)


def _kuaishou_video_url(photo: dict) -> str | None:
    url = photo.get("photoUrl")
    if url:
        return url
    for adaptation in (photo.get("manifest") or {}).get("adaptationSet") or []:
        for representation in adaptation.get("representation") or []:
            for key in ("url", "backupUrl"):
                url = representation.get(key)
                if url:
                    return url
    return None


def _download_kuaishou(url: str, output_dir: Path) -> DownloadedVideo:
    headers = KUAISHOU_HEADERS.copy()
    client = httpx.Client(
        headers=headers,
        follow_redirects=True,
        timeout=httpx.Timeout(20.0),
        **_client_proxy_kwargs(),
    )
    try:
        resolved = str(client.get(url).url)
        photo_id = extract_video_id(resolved, "kuaishou") or ""
        if not photo_id:
            match = re.search(r"short-video/(\w+)", resolved)
            photo_id = match.group(1) if match else ""

        existing = _existing_file(output_dir, photo_id)
        if existing:
            print(f"⏭️  已下载过快手视频：{existing.name}")
            return DownloadedVideo(
                video_path=existing,
                source_url=url,
                platform="kuaishou",
                video_id=photo_id,
            )

        if not photo_id:
            raise DownloadError(f"无法从快手链接解析视频 ID：{resolved}")

        cookie_string = _kuaishou_cookie_string(client)
        client.headers["Cookie"] = cookie_string
        client.headers["Referer"] = resolved

        payload = {
            "operationName": "visionVideoDetail",
            "variables": {"photoId": photo_id, "page": "detail"},
            "query": KUAISHOU_GRAPHQL_QUERY,
        }
        response = client.post(KUAISHOU_GRAPHQL_URL, json=payload)
        if response.status_code != 200:
            raise DownloadError(
                f"快手接口返回 HTTP {response.status_code}：{response.text[:120]}"
            )
        try:
            data = response.json()
        except json.JSONDecodeError as e:
            raise DownloadError(
                f"快手接口返回非 JSON 响应：{response.text[:120]!r}"
            ) from e

        data_payload = data.get("data") or {}
        result_code = data.get("result") or data_payload.get("result")
        if result_code or data_payload.get("captcha"):
            raise DownloadError(
                "快手接口触发风控验证。请使用浏览器登录快手后，把浏览器里的完整 "
                "Cookie 配置到 .env 的 KUAISHOU_COOKIE 后重试。"
            )

        detail = data_payload.get("visionVideoDetail") or {}
        photo = detail.get("photo") or {}
        media_url = _kuaishou_video_url(photo)
        if not photo.get("id") or not media_url:
            raise DownloadError(
                "快手接口未返回可下载的视频地址（可能需要设置 KUAISHOU_COOKIE）"
            )

        target = output_dir / f"{photo['id']}.mp4"
        _stream_download(
            media_url,
            target,
            headers={"Referer": resolved},
        )
        return DownloadedVideo(
            video_path=target,
            source_url=url,
            platform="kuaishou",
            video_id=str(photo["id"]),
            title=str(photo.get("caption") or ""),
            duration=_duration_seconds(photo.get("duration")),
            thumbnail=photo.get("coverUrl"),
        )
    finally:
        client.close()


# ---------------------------------------------------------------------------
# public API
# ---------------------------------------------------------------------------

_DOWNLOADERS: dict[str, Callable[[str, Path], DownloadedVideo]] = {
    "youtube": _download_youtube,
    "bilibili": _download_bilibili,
    "douyin": _download_douyin,
    "kuaishou": _download_kuaishou,
}


def download_video(source: str, output_dir: str | Path | None = None) -> DownloadedVideo:
    """Download an online video and return its local path.

    ``source`` may be a plain URL or a complete share message containing a
    URL (common for Douyin / Kuaishou).
    """
    url = extract_url(source)
    if not url:
        raise DownloadError(f"未在输入中找到视频链接：{source!r}")

    platform = detect_platform(url)
    if not platform:
        raise DownloadError(
            f"暂不支持该视频平台或链接格式无效：{url}（支持 YouTube / Bilibili / 抖音 / 快手）"
        )

    directory = Path(output_dir).expanduser() if output_dir else _download_dir()
    directory.mkdir(parents=True, exist_ok=True)

    print(f"⬇️  正在下载 {platform} 视频：{url}")
    try:
        return _DOWNLOADERS[platform](url, directory)
    except DownloadError:
        raise
    except Exception as e:
        raise DownloadError(f"{platform} 视频下载失败：{e}") from e


__all__ = [
    "DownloadedVideo",
    "detect_platform",
    "download_video",
    "extract_url",
    "extract_video_id",
    "is_supported_video_url",
]
